#!/bin/sh

if nginx -V 2>&1 | grep -q ubus; then
	if [ -z "$(cat /etc/nginx/conf.d/luci.locations | grep ubus)" ]; then
		cat <<EOT >> /etc/nginx/conf.d/luci.locations

location /ubus {
        ubus_interpreter;
        ubus_socket_path /var/run/ubus.sock;
        ubus_parallel_req 2;
}
EOT
	fi
fi

exit 0
